# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mech_acn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0emech_acn.proto\x12\x1a\x61\x65\x61.valory.mech_acn.v0_1_0"\xa8\x01\n\x0eMechAcnMessage\x12L\n\x04\x64\x61ta\x18\x05 \x01(\x0b\x32<.aea.valory.mech_acn.v0_1_0.MechAcnMessage.Data_PerformativeH\x00\x1a\x38\n\x11\x44\x61ta_Performative\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\tB\x0e\n\x0cperformativeb\x06proto3'
)


_MECHACNMESSAGE = DESCRIPTOR.message_types_by_name["MechAcnMessage"]
_MECHACNMESSAGE_DATA_PERFORMATIVE = _MECHACNMESSAGE.nested_types_by_name[
    "Data_Performative"
]
MechAcnMessage = _reflection.GeneratedProtocolMessageType(
    "MechAcnMessage",
    (_message.Message,),
    {
        "Data_Performative": _reflection.GeneratedProtocolMessageType(
            "Data_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _MECHACNMESSAGE_DATA_PERFORMATIVE,
                "__module__": "mech_acn_pb2"
                # @@protoc_insertion_point(class_scope:aea.valory.mech_acn.v0_1_0.MechAcnMessage.Data_Performative)
            },
        ),
        "DESCRIPTOR": _MECHACNMESSAGE,
        "__module__": "mech_acn_pb2"
        # @@protoc_insertion_point(class_scope:aea.valory.mech_acn.v0_1_0.MechAcnMessage)
    },
)
_sym_db.RegisterMessage(MechAcnMessage)
_sym_db.RegisterMessage(MechAcnMessage.Data_Performative)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _MECHACNMESSAGE._serialized_start = 47
    _MECHACNMESSAGE._serialized_end = 215
    _MECHACNMESSAGE_DATA_PERFORMATIVE._serialized_start = 143
    _MECHACNMESSAGE_DATA_PERFORMATIVE._serialized_end = 199
# @@protoc_insertion_point(module_scope)
