# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mech_acn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0emech_acn.proto\x12\x1a\x61\x65\x61.valory.mech_acn.v0_1_0"\x8a\x04\n\x0eMechAcnMessage\x12R\n\x07request\x18\x05 \x01(\x0b\x32?.aea.valory.mech_acn.v0_1_0.MechAcnMessage.Request_PerformativeH\x00\x12T\n\x08response\x18\x06 \x01(\x0b\x32@.aea.valory.mech_acn.v0_1_0.MechAcnMessage.Response_PerformativeH\x00\x1a\xa7\x01\n\x06Status\x12H\n\x06status\x18\x01 \x01(\x0e\x32\x38.aea.valory.mech_acn.v0_1_0.MechAcnMessage.Status.Status"S\n\x06Status\x12\x15\n\x11REQUEST_NOT_FOUND\x10\x00\x12\x12\n\x0e\x44\x41TA_NOT_READY\x10\x01\x12\t\n\x05READY\x10\x02\x12\x13\n\x0fREQUEST_EXPIRED\x10\x03\x1a*\n\x14Request_Performative\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x1ah\n\x15Response_Performative\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x41\n\x06status\x18\x02 \x01(\x0b\x32\x31.aea.valory.mech_acn.v0_1_0.MechAcnMessage.StatusB\x0e\n\x0cperformativeb\x06proto3'
)


_MECHACNMESSAGE = DESCRIPTOR.message_types_by_name["MechAcnMessage"]
_MECHACNMESSAGE_STATUS = _MECHACNMESSAGE.nested_types_by_name["Status"]
_MECHACNMESSAGE_REQUEST_PERFORMATIVE = _MECHACNMESSAGE.nested_types_by_name[
    "Request_Performative"
]
_MECHACNMESSAGE_RESPONSE_PERFORMATIVE = _MECHACNMESSAGE.nested_types_by_name[
    "Response_Performative"
]
_MECHACNMESSAGE_STATUS_STATUS = _MECHACNMESSAGE_STATUS.enum_types_by_name["Status"]
MechAcnMessage = _reflection.GeneratedProtocolMessageType(
    "MechAcnMessage",
    (_message.Message,),
    {
        "Status": _reflection.GeneratedProtocolMessageType(
            "Status",
            (_message.Message,),
            {
                "DESCRIPTOR": _MECHACNMESSAGE_STATUS,
                "__module__": "mech_acn_pb2"
                # @@protoc_insertion_point(class_scope:aea.valory.mech_acn.v0_1_0.MechAcnMessage.Status)
            },
        ),
        "Request_Performative": _reflection.GeneratedProtocolMessageType(
            "Request_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _MECHACNMESSAGE_REQUEST_PERFORMATIVE,
                "__module__": "mech_acn_pb2"
                # @@protoc_insertion_point(class_scope:aea.valory.mech_acn.v0_1_0.MechAcnMessage.Request_Performative)
            },
        ),
        "Response_Performative": _reflection.GeneratedProtocolMessageType(
            "Response_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _MECHACNMESSAGE_RESPONSE_PERFORMATIVE,
                "__module__": "mech_acn_pb2"
                # @@protoc_insertion_point(class_scope:aea.valory.mech_acn.v0_1_0.MechAcnMessage.Response_Performative)
            },
        ),
        "DESCRIPTOR": _MECHACNMESSAGE,
        "__module__": "mech_acn_pb2"
        # @@protoc_insertion_point(class_scope:aea.valory.mech_acn.v0_1_0.MechAcnMessage)
    },
)
_sym_db.RegisterMessage(MechAcnMessage)
_sym_db.RegisterMessage(MechAcnMessage.Status)
_sym_db.RegisterMessage(MechAcnMessage.Request_Performative)
_sym_db.RegisterMessage(MechAcnMessage.Response_Performative)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _MECHACNMESSAGE._serialized_start = 47
    _MECHACNMESSAGE._serialized_end = 569
    _MECHACNMESSAGE_STATUS._serialized_start = 236
    _MECHACNMESSAGE_STATUS._serialized_end = 403
    _MECHACNMESSAGE_STATUS_STATUS._serialized_start = 320
    _MECHACNMESSAGE_STATUS_STATUS._serialized_end = 403
    _MECHACNMESSAGE_REQUEST_PERFORMATIVE._serialized_start = 405
    _MECHACNMESSAGE_REQUEST_PERFORMATIVE._serialized_end = 447
    _MECHACNMESSAGE_RESPONSE_PERFORMATIVE._serialized_start = 449
    _MECHACNMESSAGE_RESPONSE_PERFORMATIVE._serialized_end = 553
# @@protoc_insertion_point(module_scope)
