name: main_workflow

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  lock_check:
    continue-on-error: False
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-15, windows-2025 ]
        python-version: [ "3.10" ]

    defaults:
      run:
        shell: bash

    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Check if dependencies can be locked
      run: uv lock --check
    - name: Install dependencies
      run: uv sync --all-groups -v

  copyright_and_dependencies_check:
    continue-on-error: False
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        python-version: [ "3.10" ]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install tomte[tox,cli]==0.6.5 tox-uv
    - name: Check copyright headers
      run: tomte check-copyright --author valory --exclude-part abci --exclude-part http_client --exclude-part ipfs --exclude-part ledger --exclude-part p2p_libp2p_client --exclude-part gnosis_safe --exclude-part gnosis_safe_proxy_factory --exclude-part multisend --exclude-part service_registry --exclude-part protocols --exclude-part abstract_abci --exclude-part abstract_round_abci --exclude-part registration_abci --exclude-part reset_pause_abci --exclude-part termination_abci --exclude-part transaction_settlement_abci --exclude-part websocket_client --exclude-part contract_subscription --exclude-part mech --exclude-part mech_interact_abci  --exclude-part http_server --exclude-part erc20
    - name: License compatibility check
      run: tox -e liccheck
    - name: Check dependencies
      run: tox -e check-dependencies
    - name: Check third-party package hashes match upstream
      run: tox -e check-third-party-hashes
    # skipping this link because of 500 errors even if the link is reachable
    - name: Check doc links
      run: tomte check-doc-links -n https://ethglobal.com/showcase/ai-mechs-dt36e -n https://marketplace.olas.network/ethereum/ai-agents/21 -n https://marketplace.olas.network/polygon/ai-agents/3
    - name: Check doc IPFS hashes
      run: tox -e check-doc-hashes

  linter_checks:
    continue-on-error: False
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        python-version: [ "3.10" ]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:  |
        pip install tomte[tox,cli]==0.6.5 tox-uv

        # Install `mdspell` for spelling checks
        sudo npm install -g markdown-spellcheck

    - name: Security checks
       # TODO: tomte check-security
      run: echo "Skipped until service is bumped"
    - name: Check packages
      run: tox -e check-packages
    - name: Check hash
      run: tox -e check-hash
    - name: Code checks
      run: tomte check-code
    - name: Check spelling
      run: tomte check-spelling
    - name: AbciApp consistency checks
    # analyse-service checks do not work properly as it is checking task execution skill which is not an ABCI skill
      run: |
        tox -e check-abci-docstrings
        tox -e check-abciapp-specs
        tox -e check-handlers
        # tox -e analyse-service 

  scan:
    name: gitleaks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v8.10.1/gitleaks_8.10.1_linux_x64.tar.gz
          tar -xzf gitleaks_8.10.1_linux_x64.tar.gz
          sudo install gitleaks /usr/bin
          pip install 'tomte[cli] @ git+https://github.com/valory-xyz/tomte.git@55a396a9b96b3738068f031ea05fabeda2723ee5'
          GITLEAKS_CONFIG=$(python -c "from tomte.configs import GITLEAKS_TOML; print(GITLEAKS_TOML)")
          gitleaks detect --config="$GITLEAKS_CONFIG" --report-format json --report-path leak_report -v

  test:
    continue-on-error: False
    needs:
      - lock_check
      - copyright_and_dependencies_check
      - linter_checks
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-15, windows-2025 ]
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]

    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - if: matrix.os == 'ubuntu-22.04'
        name: Install dependencies (ubuntu-22.04)
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get autoremove
          sudo apt-get autoclean
          pip install tomte[tox]==0.6.5 tox-uv
          pip install --user --upgrade setuptools

      - if: matrix.os == 'ubuntu-22.04'
        name: Packages unit tests ubuntu-22.04
        run: |
          tox -e py${{ matrix.python-version }}-linux

      - if: matrix.os == 'macos-15'
        name: Install dependencies (macos-15)
        run: |
          pip install tomte[tox]==0.6.5 tox-uv
          pip install --user --upgrade setuptools

      - if: matrix.os == 'macos-15'
        name: Packages unit tests macos-15
        run: |
          tox -e py${{ matrix.python-version }}-darwin

      - if: matrix.os == 'windows-2025'
        name: Install dependencies (windows-2025)
        run: |
          python -m pip install -U pip
          pip install tomte[tox]==0.6.5 tox-uv
          pip install --upgrade setuptools

      - if: matrix.os == 'windows-2025'
        name: Packages unit tests windows-2025
        run: |
          tox -e py${{ matrix.python-version }}-win

      - if: matrix.os == 'ubuntu-22.04'
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  all_checks_passed:
    name: All checks passed
    if: always()
    needs:
      - lock_check
      - copyright_and_dependencies_check
      - linter_checks
      - scan
      - test
    runs-on: ubuntu-22.04
    steps:
      - name: Fail if any required job failed or was cancelled
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
      - run: echo "All required checks passed."
