name: main_workflow

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lock_check:
    continue-on-error: False
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-15, windows-2025 ]
        python-version: [ "3.10" ]

    defaults:
      run:
        shell: bash

    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Check if dependencies can be locked
      run: uv lock --check
    - name: Install dependencies
      run: uv sync --all-groups -v

  copyright_and_dependencies_check:
    continue-on-error: False
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        python-version: [ "3.10" ]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install tomte[tox,cli]==0.6.2 tox-uv
    - name: Check copyright headers
      run: tomte check-copyright --author valory --exclude-part abci --exclude-part http_client --exclude-part ipfs --exclude-part ledger --exclude-part p2p_libp2p_client --exclude-part gnosis_safe --exclude-part gnosis_safe_proxy_factory --exclude-part multisend --exclude-part service_registry --exclude-part contracts --exclude-part skills --exclude-part protocols --exclude-part abstract_abci --exclude-part abstract_round_abci --exclude-part registration_abci --exclude-part reset_pause_abci --exclude-part termination_abci --exclude-part transaction_settlement_abci --exclude-part websocket_client --exclude-part contract_subscription --exclude-part mech --exclude-part mech_interact_abci  --exclude-part http_server
    - name: License compatibility check
      run: tox -e liccheck
# TODO: reactivate once false positives are fixed
#    - name: Check dependencies
#      run: tox -e check-dependencies
    - name: Check doc links
      run: tomte check-doc-links
    - name: Check doc IPFS hashes
      run: tox -e check-doc-hashes

  linter_checks:
    continue-on-error: False
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        python-version: [ "3.10" ]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:  |
        pip install tomte[tox,cli]==0.6.2 tox-uv

        # Install `mdspell` for spelling checks
        sudo npm install -g markdown-spellcheck

    - name: Security checks
       # TODO: tomte check-security
      run: echo "Skipped until service is bumped"
    - name: Check packages
      run: tox -e check-packages
    - name: Check hash
      run: tox -e check-hash
    - name: Code checks
      run: tomte check-code
    - name: Check spelling
      run: tomte check-spelling
    - name: AbciApp consistency checks
    # analyse-service checks do not work properly as it is checking task execution skill which is not an ABCI skill
      run: |
        tox -e check-abci-docstrings
        tox -e check-abciapp-specs
        tox -e check-handlers
        # tox -e analyse-service 

  scan:
    name: gitleaks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v8.10.1/gitleaks_8.10.1_linux_x64.tar.gz && \
          tar -xzf gitleaks_8.10.1_linux_x64.tar.gz && \
          sudo install gitleaks /usr/bin && \
          gitleaks detect --report-format json --report-path leak_report -v

  unit_tests:
    continue-on-error: False
    needs:
      - lock_check
      - copyright_and_dependencies_check
      - linter_checks
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-15, windows-2025 ]
        python-version: [ "3.10", "3.14" ]
        include:
          - os: ubuntu-22.04
            python-version: "3.11"
          - os: ubuntu-22.04
            python-version: "3.12"
          - os: ubuntu-22.04
            python-version: "3.13"

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - if: matrix.os == 'ubuntu-22.04'
        name: Install dependencies (ubuntu-22.04)
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get autoremove
          sudo apt-get autoclean
          pip install tomte[tox,cli]==0.6.2 tox-uv
          pip install --user --upgrade setuptools
      - if: matrix.os == 'ubuntu-22.04'
        name: Unit tests ubuntu-22.04
        run: tox -e py${{ matrix.python-version }}-linux
      - if: matrix.os == 'macos-15'
        name: Install dependencies (macos-15)
        run: |
          pip install tomte[tox,cli]==0.6.2 tox-uv
          pip install --user --upgrade setuptools
      - if: matrix.os == 'macos-15'
        name: Unit tests macos-15
        run: tox -e py${{ matrix.python-version }}-darwin
      - if: matrix.os == 'windows-2025'
        name: Install dependencies (windows-2025)
        run: |
          python -m pip install -U pip
          pip install tomte[tox,cli]==0.6.2 tox-uv
          pip install --upgrade setuptools
      - if: matrix.os == 'windows-2025'
        name: Unit tests windows-2025
        run: tox -e py${{ matrix.python-version }}-win

  integration_tests:
    continue-on-error: True
    needs:
      - unit_tests
    runs-on: ubuntu-22.04

    timeout-minutes: 120

    env:
      OPENAI_SECRET_KEY: ${{ secrets.OPENAI_SECRET_KEY }}
      OPENAI_SECRET_KEYS: ${{ secrets.OPENAI_SECRET_KEYS }}
      STABILITY_API_KEY: ${{ secrets.STABILITY_API_KEY }}
      STABILITY_API_KEYS: ${{ secrets.STABILITY_API_KEYS }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      GOOGLE_API_KEYS: ${{ secrets.GOOGLE_API_KEYS }}
      GOOGLE_ENGINE_ID: ${{ secrets.GOOGLE_ENGINE_ID }}
      GOOGLE_ENGINE_IDS: ${{ secrets.GOOGLE_ENGINE_IDS }}
      CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      CLAUDE_API_KEYS: ${{ secrets.CLAUDE_API_KEYS }}
      REPLICATE_API_KEY: ${{ secrets.REPLICATE_API_KEY }}
      REPLICATE_API_KEYS: ${{ secrets.REPLICATE_API_KEYS }}
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      NEWS_API_KEYS: ${{ secrets.NEWS_API_KEYS }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      OPENROUTER_API_KEYS: ${{ secrets.OPENROUTER_API_KEYS }}
      GNOSIS_RPC_URL: ${{ secrets.GNOSIS_RPC_URL }}
      GNOSIS_RPC_URLS: ${{ secrets.GNOSIS_RPC_URLS }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GEMINI_API_KEYS: ${{ secrets.GEMINI_API_KEYS }}
      GRAPH_API_KEY: ${{ secrets.GRAPH_API_KEY }}
      GRAPH_API_KEYS: ${{ secrets.GRAPH_API_KEYS }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get autoremove
          sudo apt-get autoclean
          pip install tomte[tox,cli]==0.6.2 tox-uv
          pip install --user --upgrade setuptools
      - name: Integration tests
        run: tox -e py3.12-integration-linux
